import Login from "@/components/login/Login";
import React from "react";

export const metadata = {
  title: "Next App - Login",
  description: "Generated by create next app",
};

export default function Page() {
  return <Login />;
}
