import Login from "@/components/login/Login";
import React from "react";
import { ToastContainer } from "react-toastify";

export const metadata = {
  title: "Next App - Login",
  description: "Generated by create next app",
};

export default function Page() {
  return (
    <div>
      <ToastContainer
        autoClose={2000}
        position="bottom-right"
        theme="colored"
        draggable
      />
      <Login />
    </div>
  );
}
