"use client";
import "bootstrap/dist/css/bootstrap.min.css";
import "../styles/main.scss";
import { ToastContainer } from "react-toastify";
import Layout from "@/components/layout/Layout";
import { usePathname } from "next/navigation";
import { AppProvider } from "./context/AppContext";

// export const metadata = {
//   title: "Next App - Login",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const pathname = usePathname();

  // ✅ Exclude Layout for login page
  if (pathname === "/login") {
    return (
      <html lang="en">
        <body>{children}</body>
      </html>
    );
  }

  return (
    <html lang="en">
      <body>
        <ToastContainer
          autoClose={1000}
          position="bottom-right"
          theme="colored"
          draggable
        />
        <AppProvider>
          <Layout>{children}</Layout>
        </AppProvider>
      </body>
    </html>
  );
}
